q1

In [27]:
import torch 

In [28]:
t = torch.arange(0,10,1)
t
t.shape

torch.Size([10])

In [29]:
t

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
reshaped_t = t.reshape((2,5))
reshaped_t

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [31]:
t2 = torch.zeros((2,5))
stacked = torch.hstack((reshaped_t , t2))
print(stacked)

tensor([[0., 1., 2., 3., 4., 0., 0., 0., 0., 0.],
        [5., 6., 7., 8., 9., 0., 0., 0., 0., 0.]])


In [32]:
t2 = torch.zeros((2,5))
st = torch.vstack((reshaped_t , t2))
print(st)

tensor([[0., 1., 2., 3., 4.],
        [5., 6., 7., 8., 9.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [33]:
unsqueezed = stacked.unsqueeze(1)
print("Original Shape was = ", stacked.shape)
print("After Unsqueezing = ", unsqueezed.shape)
print(unsqueezed)

Original Shape was =  torch.Size([2, 10])
After Unsqueezing =  torch.Size([2, 1, 10])
tensor([[[0., 1., 2., 3., 4., 0., 0., 0., 0., 0.]],

        [[5., 6., 7., 8., 9., 0., 0., 0., 0., 0.]]])


In [34]:
squeezed = unsqueezed.squeeze(1)
print("Again got back to shape = ", squeezed.shape)


Again got back to shape =  torch.Size([2, 10])


q2

In [35]:
import torch 
import numpy as np
t1 = torch.randn(2,3,4)
print(t1.size())
t2 = t1.permute(2,1,0)
print("After permute = \n",t2.size())

torch.Size([2, 3, 4])
After permute = 
 torch.Size([4, 3, 2])


q3

In [36]:
print(t1)

tensor([[[ 1.0946, -0.3422, -0.7359,  0.3114],
         [-0.1689, -0.6065, -1.2940, -0.1895],
         [ 1.4947, -0.6921, -1.8405, -0.2273]],

        [[-0.2339,  0.1880, -0.0966,  1.1273],
         [-1.4253, -0.5303,  0.0756, -0.7297],
         [ 0.3345,  0.2916, -1.1151,  0.5888]]])


In [37]:
print(t1[1,2,3])

tensor(0.5888)


q4

In [38]:
n1 = np.array([1, 2, 3])
print("N1 is currently of type = ", type(n1))
n1 = torch.from_numpy(n1)
print("N1 is currently of type = ", type(n1))
n1 = n1.cpu().numpy()
print("N1 is currently of type = ", type(n1))

N1 is currently of type =  <class 'numpy.ndarray'>
N1 is currently of type =  <class 'torch.Tensor'>
N1 is currently of type =  <class 'numpy.ndarray'>


q5

In [39]:
r1 = torch.randn((7, 7))
print(r1.shape)
print(r1)

torch.Size([7, 7])
tensor([[-0.2155,  0.6672,  0.0746,  0.6943, -1.3940, -1.0986,  1.2697],
        [-1.7178, -0.8308,  0.2577, -0.8919, -0.6432, -0.4213,  0.4766],
        [ 0.6666, -1.5489,  0.2400, -1.1055,  1.2209, -1.4995,  0.6585],
        [ 0.2492,  0.5609,  0.4822, -0.7999,  0.9750, -1.5140, -2.2039],
        [-0.8670, -0.9286, -2.0181, -1.5178, -0.8005, -0.9855,  0.0238],
        [-0.4535,  0.4476,  0.8965,  1.1175, -0.1509,  0.7373,  0.8417],
        [-1.4866,  1.0906, -0.1496,  0.0466,  1.3156, -0.4388,  0.4872]])


q6

In [40]:
r2 = torch.randn((1, 7))
res = torch.matmul(r1, r2.T)
print(res.shape)
print(res)

torch.Size([7, 1])
tensor([[-0.4187],
        [ 1.2537],
        [-4.9044],
        [-6.2787],
        [-1.4667],
        [ 3.7091],
        [ 2.9868]])


q7

In [41]:
tens1 = torch.randn((2,3))
tens2 = torch.randn((2,3))
device = 'cuda' if torch.cuda.is_available() else 'cpu'
tens1_on_gpu = tens1.to(device)
tens2_on_gpu = tens2.to(device)
tens1_on_gpu , tens2_on_gpu

(tensor([[ 5.6931e-01, -3.2981e-02, -9.4031e-01],
         [ 7.6188e-01,  7.7518e-01, -1.7077e-04]], device='cuda:0'),
 tensor([[-0.4135,  2.4606, -0.4387],
         [-1.7441, -0.1893,  0.3955]], device='cuda:0'))

q8

In [42]:
res = torch.matmul(tens1, tens2.T)
print(res, res.device)

tensor([[ 0.0959, -1.3586],
        [ 1.5925, -1.4756]]) cpu


In [43]:
res1 = torch.matmul(tens1_on_gpu, tens2_on_gpu.T)
print(res1, res1.device)

tensor([[ 0.0959, -1.3586],
        [ 1.5925, -1.4756]], device='cuda:0') cuda:0


q9

In [44]:
print("Max value ", res.max())
print("Min value ", res.min())

Max value  tensor(1.5925)
Min value  tensor(-1.4756)


q10

In [45]:
print("Max Index", res.argmax())
print("Min Index", res.argmin())

Max Index tensor(2)
Min Index tensor(3)


q11

In [46]:
torch.manual_seed(7)
ti = torch.randn((1, 1, 1, 10))
print(ti, "\nBefore - ", ti.shape)
ti = ti.squeeze(0, 1, 2)
print(ti, "\nAfter - ", ti.shape)


tensor([[[[-0.1468,  0.7861,  0.9468, -1.1143,  1.6908, -0.8948, -0.3556,
            1.2324,  0.1382, -1.6822]]]]) 
Before -  torch.Size([1, 1, 1, 10])
tensor([-0.1468,  0.7861,  0.9468, -1.1143,  1.6908, -0.8948, -0.3556,  1.2324,
         0.1382, -1.6822]) 
After -  torch.Size([10])
